### ISSUE TITLE
TODO: HTTP response header

### ISSUE THREAD

**Issue by jjongs2** [SOONG-E/Webserv#1]
## TODO

- [x] RFC 공식 문서 참고하여 주석으로 context 명시
- [ ] 각 헤더 필드의 기본값 설정 (필요한 경우에만)
- [ ] 기본값 상수화
- [ ] 헤더 필드에 파싱된 값 추가 시 기본값 삭제
